import type { Project, SkillCategory } from "./types"

export const projects: Project[] = [
  {
    id: "defi-dashboard",
    title: "DeFi Dashboard",
    description: "A comprehensive dashboard for tracking DeFi investments across multiple chains",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["React", "Ethers.js", "Web3", "DeFi"],
    highlights: [
      "Multi-chain portfolio tracking",
      "Real-time price updates",
      "Yield farming analytics",
      "Transaction history visualization",
    ],
    demoUrl: "https://defi-dashboard.example.com",
    githubUrl: "https://github.com/chrisweb3/defi-dashboard",
    detailsUrl: "/projects/defi-dashboard",
  },
  {
    id: "nft-marketplace",
    title: "NFT Marketplace",
    description: "A decentralized marketplace for creating, buying, and selling NFTs",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Next.js", "Solidity", "IPFS", "NFT"],
    highlights: ["Gasless minting", "Multi-format NFT support", "Royalty distribution", "Social features"],
    demoUrl: "https://nft-marketplace.example.com",
    githubUrl: "https://github.com/chrisweb3/nft-marketplace",
    detailsUrl: "/projects/nft-marketplace",
  },
  {
    id: "dao-governance",
    title: "DAO Governance Platform",
    description: "A governance platform for decentralized autonomous organizations",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["TypeScript", "Solidity", "The Graph", "DAO"],
    highlights: [
      "On-chain voting",
      "Proposal creation and management",
      "Token-weighted governance",
      "Delegation system",
    ],
    demoUrl: "https://dao-governance.example.com",
    githubUrl: "https://github.com/chrisweb3/dao-governance",
    detailsUrl: "/projects/dao-governance",
  },
  {
    id: "crypto-wallet",
    title: "Multi-Chain Crypto Wallet",
    description: "A secure, non-custodial wallet supporting multiple blockchains",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["React Native", "Blockchain", "Security"],
    highlights: [
      "Multi-chain support",
      "Hardware wallet integration",
      "Biometric authentication",
      "Transaction simulation",
    ],
    githubUrl: "https://github.com/chrisweb3/crypto-wallet",
    detailsUrl: "/projects/crypto-wallet",
  },
  {
    id: "defi-protocol",
    title: "DeFi Lending Protocol",
    description: "A decentralized lending and borrowing protocol with innovative features",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Solidity", "DeFi", "Smart Contracts"],
    highlights: [
      "Variable and fixed interest rates",
      "Flash loans",
      "Collateralization optimization",
      "Risk assessment framework",
    ],
    githubUrl: "https://github.com/chrisweb3/defi-protocol",
    detailsUrl: "/projects/defi-protocol",
  },
  {
    id: "blockchain-explorer",
    title: "Custom Blockchain Explorer",
    description: "A feature-rich explorer for a custom blockchain network",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Node.js", "GraphQL", "Blockchain"],
    highlights: [
      "Real-time transaction tracking",
      "Smart contract verification",
      "Advanced analytics",
      "API for developers",
    ],
    demoUrl: "https://blockchain-explorer.example.com",
    githubUrl: "https://github.com/chrisweb3/blockchain-explorer",
    detailsUrl: "/projects/blockchain-explorer",
  },
]

export const skillCategories: SkillCategory[] = [
  {
    name: "Blockchain & Web3",
    icon: "🔗",
    skills: [
      "Ethereum",
      "Solidity",
      "Smart Contracts",
      "Web3.js",
      "Ethers.js",
      "Hardhat",
      "Truffle",
      "IPFS",
      "The Graph",
    ],
  },
  {
    name: "Frontend Development",
    icon: "🖥️",
    skills: ["React", "Next.js", "TypeScript", "JavaScript", "Tailwind CSS", "HTML/CSS", "Redux", "React Query"],
  },
  {
    name: "Backend Development",
    icon: "⚙️",
    skills: ["Node.js", "Express", "GraphQL", "REST APIs", "MongoDB", "PostgreSQL", "Firebase"],
  },
  {
    name: "DeFi & NFTs",
    icon: "💰",
    skills: ["Yield Farming", "Liquidity Pools", "AMMs", "NFT Standards", "Tokenomics", "DAO Governance"],
  },
  {
    name: "Tools & DevOps",
    icon: "🛠️",
    skills: ["Git", "GitHub Actions", "Docker", "AWS", "Vercel", "CI/CD", "Testing"],
  },
  {
    name: "Other Skills",
    icon: "🧠",
    skills: ["Technical Writing", "Project Management", "UI/UX Design", "Security Auditing", "Cryptography"],
  },
]
